const names = require('./04-names')
const sayHi = require('./05-utils')
const data = require('./06-alternative-flavor')
var a = require('./07-mind-grenade')
// sayHi('123')
// sayHi(names.john)
// sayHi(names.peter)